name: dine_dealer
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.7
  get: ^4.7.2
  dio: ^5.8.0+1
  either_dart: ^1.0.0
  flutter_secure_storage: ^4.2.1
  intl_utils: ^2.8.10

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.15

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/fonts/
  
  fonts:
    - family: Manrope
      fonts:
        - asset: assets/fonts/manrope/Manrope-Bold.ttf
          weight: 700

        - asset: assets/fonts/manrope/Manrope-ExtraBold.ttf
          weight: 800

        - asset: assets/fonts/manrope/Manrope-ExtraLight.ttf
          weight: 200

        - asset: assets/fonts/manrope/Manrope-Light.ttf
          weight: 300

        - asset: assets/fonts/manrope/Manrope-Medium.ttf
          weight: 500

        - asset: assets/fonts/manrope/Manrope-Regular.ttf
          weight: 400

        - asset: assets/fonts/manrope/Manrope-SemiBold.ttf
          weight: 600

    - family: RobotoSerif
      fonts:
        - asset: assets/fonts/roboto/RobotoSerif-Bold.ttf
          weight: 700

        - asset: assets/fonts/roboto/RobotoSerif-ExtraBold.ttf
          weight: 800

        - asset: assets/fonts/roboto/RobotoSerif-ExtraLight.ttf
          weight: 200

        - asset: assets/fonts/roboto/RobotoSerif-Light.ttf
          weight: 300

        - asset: assets/fonts/roboto/RobotoSerif-Medium.ttf
          weight: 500

        - asset: assets/fonts/roboto/RobotoSerif-Regular.ttf
          weight: 400

        - asset: assets/fonts/roboto/RobotoSerif-SemiBold.ttf
          weight: 600

flutter_gen:
  output: lib/core/assets/
  line_length: 100

  integrations:
    flutter_svg: true


flutter_intl:
  enabled: true
  main_locale: en
  class_name: L10n
  arb_dir: lib/core/l10n/arb
  output_dir: lib/core/l10n/generated


